inherit_from:
  - .rubocop_todo.yml
  - .rubocop_airbnb.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  
Rails:
  Enabled: true

AllCops:
  NewCops: enable
  Exclude:
   - 'db/**/*'
   - 'config/**/*'
   - 'script/**/*'
   - 'node_modules/**/*'
   - 'bin/*'
   - '**/Gemfile'
   - 'vendor/**/*'
   - '.git/**/*'
   - 'shift_schedule/spec/spec_helper.rb'
   - 'lib/**/*'
   - 'shift_schedule/lib/tasks/auto_annotate_models.rake'
   - 'shift_schedule/bin/bundle'
   - 'shift_schedule/config/*'
   - 'shift_schedule/config/**/*'
   - 'spec/spec_helper.rb'
Layout/LineLength:
  Max: 200

