volumes:
  postgres_data:

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env 
    platform: linux/arm64
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - selenium_chrome
    tty: true
    stdin_open: true
    networks:
      - default
    environment:
      - SELENIUM_DRIVER_URL=http://selenium_chrome:4444/wd/hub
      - CHROME_BIN=/usr/local/bin/google-chrome
      - CHROMEDRIVER_PATH=/usr/local/bin/chromedriver
      - DATABASE_HOST=db
      - RAILS_ENV=test

  selenium_chrome:
    image: seleniarm/standalone-chromium:latest
    platform: linux/arm64
    ports:
      - "4444:4444"
    logging:
      driver: json-file

  db:
    image: postgres:14
    platform: linux/arm64
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    networks:
      - default
    ports:
       - '5432:5432'
