version: '3'

services:
  mysql:
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - default
    ports:
      - '33306:3306'
    command: --default-authentication-plugin=mysql_native_password

  web:
    build:
      context: .
      dockerfile: Dockerfile.ci
    container_name: potepanec_app
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - '3000:3000'
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: mysql
      REDIS_URL: "redis://redis:6379"
      SELENIUM_DRIVER_URL: "http://selenium_chrome:4444/wd/hub"
      GOOGLE_CHROME_BIN: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
      CHROMEDRIVER_PATH: /usr/local/bin/chromedriver
    depends_on:
      - mysql
      - redis
      - selenium_chrome
    networks:
      - default

  selenium_chrome:
    image: seleniarm/standalone-chromium:latest
    ports:
      - 4444:4444
    networks:
      - default
    logging:
      driver: none
