version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    image: mysql:8.0
    platform: linux/x86_64
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
    environment:
    - "SELENIUM_DRIVER_URL=http://selenium_chrome:4444/wd/hub"
  selenium_chrome:
    image: selenium/standalone-chrome-debug
    platform: linux/x86_64
    logging:
      driver: none
  db:
    image: mysql:5.7
    platform: linux/x86_64
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
volumes:
  db-volume:
