FROM ruby:3.0.4

RUN apt-get update -qq && apt-get install -y nodejs yarn

WORKDIR /app
COPY Gemfile /app/Gemfile
COPY Gemfile.lock /app/Gemfile.lock

RUN bundle install

COPY package.json /app/package.json
COPY yarn.lock /app/yarn.lock

COPY . /app

RUN bundle exec rails assets:precompile

EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0"]
