FROM ruby:3.0.4-buster

RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys B7B3B788A8D3785C

RUN apt-get update \
  && apt-get install -y wget gnupg2 \
  && curl -sL https://deb.nodesource.com/setup_14.x | bash - \
  && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
  && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
  && wget https://dev.mysql.com/get/mysql-apt-config_0.8.22-1_all.deb \
  && DEBIAN_FRONTEND=noninteractive dpkg -i mysql-apt-config_0.8.22-1_all.deb \
  && apt-get update --allow-insecure-repositories \
  && apt-get remove -y \
    libmariadbclient18 \
    libmariadbclient-dev-compat \
    libmariadbclient-dev \
  && apt-get install -y --allow-unauthenticated \
    default-mysql-client \
    libxml2-dev \
    libxslt-dev \
    libc6-dev \
    nodejs \
    yarn \
    zip \
  && gem install foreman \
  && gem install bundler:2.5.14 \
  && apt-get clean

RUN mkdir /potepanec
WORKDIR /potepanec
COPY . /potepanec
RUN bundle install
