volumes:
  postgres_data:
  vendor_bundle:
  node_modules:
  storage:
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    platform: linux/x86_64
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - selenium_chrome
    tty: true
    stdin_open: true
    networks:
      - default
    environment:
      - SELENIUM_DRIVER_URL=http://selenium_chrome:4444/wd/hub
      - CHROME_BIN=/usr/local/bin/google-chrome
      - CHROMEDRIVER_PATH=/usr/local/bin/chromedriver
      - POSTGRES_PASSWORD=password

  selenium_chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    platform: linux/x86_64
    logging:
      driver: none

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - default
    ports:
      - '5432:5432'
