version: '3'
services:
  selenium_chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
  web:
    build: .
    command: bundle exec rails s -b '0.0.0.0'
    environment:
      - CHROMEDRIVER_URL=http://selenium_chrome:4444/wd/hub
    depends_on:
      - selenium_chrome
    ports:
      - "3000:3000"
