version: 2.1

orbs:
  heroku: circleci/heroku@2.0
  browser-tools: circleci/browser-tools@1.4.0

jobs:
  rspec:
    working_directory: ~/potepanec
    docker:
      - image: cimg/ruby:3.0.4
      - image: cimg/node:20.10
    environment:
      RAILS_ENV: test
    resource_class: small
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y wget unzip
            wget https://chromedriver.storage.googleapis.com/91.0.4472.101/chromedriver_linux64.zip
            sudo unzip chromedriver_linux64.zip -d /usr/local/bin/
            sudo chmod +x /usr/local/bin/chromedriver
      - run:
          name: Install Chrome
          command: |
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo apt-get update
            sudo apt-get install -y \
            fonts-liberation \
            libatk-bridge2.0-0 \
            libatk1.0-0 \
            libatspi2.0-0 \
            libcups2 \
            libgbm1 \
            libgtk-3-0 \
            libnspr4 \
            libnss3 \
            libu2f-udev \
            libxcomposite1 \
            libxdamage1 \
            xdg-utils
            sudo dpkg -i google-chrome-stable_current_amd64.deb
            sudo apt-get install -f
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Install Yarn
          command: npm install -g yarn
      - run:
         name: Bundle Install
         command: bundle install
      - run:
          name: Webpack Compile
          command: bundle exec bin/webpack
      - run:
          name: Setup environment variable
          command: |
            echo "export COMPOSE_FILE=docker-compose.ci.yml" >> $BASH_ENV
      - run:
          name: Start containers and verify it is working
          command: |
            set -x
            docker-compose up -d
            docker exec potepanec_app curl -4 --retry 10 --retry-delay 3 --retry-connrefused http://localhost:3000
      - run:
          name: Run rspec
          command: docker-compose exec potepanec rspec

  rubocop:
    working_directory: ~/potepanec
    docker:
      - image: cimg/ruby:3.0.4
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          keys:
            - gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gemfiles-{{ .Branch }}-
            - gemfiles-master-
      - run: bundle config --local path vendor/bundle
      - run:
          name: bundle install
          command: bundle check || bundle install --jobs=8 --clean
      - run:
          name: Run rubocop
          command: bundle exec rubocop --parallel
      - save_cache:
          key: gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

  heroku_deploy:
    working_directory: ~/potepanec
    executor: heroku/default
    resource_class: small
    steps:
      - checkout
      - heroku/install
      - run:
          name: Deploy
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master
      - run:
          name: Run post-deploy tasks
          command: |
            heroku run bin/rails db:migrate -a $HEROKU_APP_NAME

workflows:
  version: 2.1
  build:
    jobs:
      - rspec
      - rubocop
      - heroku_deploy:
          requires:
            - rspec
            - rubocop
