version: 2.1

orbs:
  heroku: circleci/heroku@2.0
  browser-tools: circleci/browser-tools@1.4.8

jobs:
  rspec:
    docker:
      - image: cimg/ruby:3.0.4-node
    environment:
      RAILS_ENV: test
      GOOGLE_CHROME_BIN: /usr/bin/google-chrome-stable
      CHROMEDRIVER_PATH: /usr/local/bin/chromedriver
    resource_class: small
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Set Chrome binary path
          command: echo "export GOOGLE_CHROME_BIN=/usr/bin/google-chrome-stable" >> $BASH_ENV
      - run:
          name: Set ChromeDriver path
          command: echo "export CHROMEDRIVER_PATH=/usr/local/bin/chromedriver" >> $BASH_ENV
      - setup_remote_docker:
          version: 20.10.18
      - run:
         name: Bundle Install
         command: bundle install
      - run:
          name: Webpack Compile
          command: |
            yarn add webpack webpack-cli
            ./bin/webpack
      - run:
          name: Setup environment variable
          command: |
            echo "export COMPOSE_FILE=docker-compose.ci.yml" >> $BASH_ENV
      - run:
          name: Set ChromeDriver cache
          command: |
            rm -rf /root/.cache/selenium/chromedriver/
      - run:
          name: Start containers and verify it is working
          command: |
            set -x
            docker-compose up -d
            docker exec potepanec_app curl -4 --retry 10 --retry-delay 3 --retry-connrefused http://localhost:3000
      - run:
          name: Run rspec
          command: docker-compose exec web bundle exec rspec

  rubocop:
    docker:
      - image: cimg/ruby:3.0.4
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          keys:
            - gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gemfiles-{{ .Branch }}-
            - gemfiles-master-
      - run: bundle config --local path vendor/bundle
      - run:
          name: bundle install
          command: bundle check || bundle install --jobs=8 --clean
      - run:
          name: Run rubocop
          command: bundle exec rubocop --parallel
      - save_cache:
          key: gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

  heroku_deploy:
    working_directory: ~/potepanec
    executor: heroku/default
    resource_class: small
    steps:
      - checkout
      - heroku/install
      - run:
          name: Deploy
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master
      - run:
          name: Run post-deploy tasks
          command: |
            heroku run bin/rails db:migrate -a $HEROKU_APP_NAME

workflows:
  version: 2.1
  build:
    jobs:
      - rspec
      - rubocop
      - heroku_deploy:
          requires:
            - rspec
            - rubocop
