version: 2.1
jobs:
  rspec:
    machine:
      image: ubuntu-2004:2022.04.2
    working_directory: ~/fitness_app01
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: update bundler
          command: |
            gem install bundler
            bundle config set path 'vendor/bundle'
            bundle install --jobs=4 --retry=3
      - save_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}
          paths:
            - ./vendor/bundle
      - run: bundle exec rails db:create RAILS_ENV=test
      - run: bundle exec rails db:schema:load RAILS_ENV=test
      - run:
          name: yarn Install
          command: yarn install
      - run: bundle exec bin/webpack
      - run:
          name: RSpec
          command: bundle exec rspec
  rubocop:
    machine:
      image: ubuntu-2004:2022.04.2
    working_directory: ~/fitness_app01
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: update bundler
          command: |
            gem install bundler
            bundle config set path 'vendor/bundle'
            bundle install --jobs=4 --retry=3
      - save_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}
          paths:
            - ./vendor/bundle
      - run: bundle exec rails db:create RAILS_ENV=test
      - run: bundle exec rails db:schema:load RAILS_ENV=test
      - run:
          name: RuboCop
          command: bundle exec rubocop
heroku_deploy:
    executor: heroku/default
    resource_class: small
    steps:
      - checkout
      - heroku/install
      - run:
          name: deploy to Heroku
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master
      - run:
          name: run post-deploy tasks
          command: |
            heroku run bin/rails db:migrate -a $HEROKU_APP_NAME

workflows:
  version: 2
  rspec_and_rubocop_workflow:
    jobs:
      - rspec
      - rubocop
