version: 2.1
jobs:
  rspec:
    machine:
      image: ubuntu-2004:2022.04.1
    steps:
      - checkout
      - run:
          name: Set up Ruby
          command: |
            rbenv install 3.0.4 -s  # Ruby 3.0.4 をインストール
            rbenv global 3.0.4
            ruby -v
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: update bundler
          command: |
            gem install bundler
            bundle config set path 'vendor/bundle'
            bundle install --jobs=4 --retry=3
      - save_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}
          paths:
            - ./vendor/bundle
      - run: bundle exec rails db:create RAILS_ENV=test
      - run: bundle exec rails db:schema:load RAILS_ENV=test
      - run:
          name: yarn Install
          command: yarn install
      - run: bundle exec bin/webpack
      - run:
          name: RSpec
          command: bundle exec rspec

  rubocop:
    machine:
      image: ubuntu-2004:2022.04.1
    steps:
      - checkout
      - run:
          name: Set up Ruby
          command: |
            rbenv install 3.0.4 -s  # Ruby 3.0.4 をインストール
            rbenv global 3.0.4
            ruby -v
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: update bundler
          command: |
            gem install bundler
            bundle config set path 'vendor/bundle'
            bundle install --jobs=4 --retry=3
      - save_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}
          paths:
            - ./vendor/bundle
      - run: bundle exec rails db:create RAILS_ENV=test
      - run: bundle exec rails db:schema:load RAILS_ENV=test
      - run:
          name: RuboCop
          command: bundle exec rubocop

workflows:
  version: 2
  rspec_and_rubocop_workflow:
    jobs:
      - rspec
      - rubocop
